AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'config.ru'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
